theme = "awesome-identity"
baseURL = "https://chafux.com"
title = "Amine Chafia - Software Developer / Salesforce"


## Profile Configurations
[params.profile]
  portrait = "/images/Profil.png"
  firstname = "Amine"
  lastname = "Chafia"
  title = "software developer"
  bio = """Software developer with experience building both the front-end and back-end of web applications.

  My passion lies in creating efficient, scalable solutions that empower users and simplify their lives.

  Beyond code, I'm deeply interested in emerging technologies. Whether it's blockchain, machine learning, or cloud-native architectures, I'm always exploring...
  """
## Contacts Configurations
[params.contacts]
  email = "chafia.amine1@gmail.com"
  github = "chafux"
  twitter = "AmineIchaf"
  linkedin = "amine-chafia"
  keybase = "amine_chafia"
  


## Actions Configurations
[params]
actions = [
  
]



## Footer Configurations
[params.footer]
  copyright = "© 2024 Amine Chafia. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true